### ISSUE TITLE
定义custom_loading_view无效？

### ISSUE THREAD

**Issue by tmxd09887** [lany192/MultiStateView#2]
`<com.lany.state.StateLayout android:id="@+id/stateLayout"
    xmlns:app="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tl="http://schemas.android.com/apk/res-auto"
    app:loadingView="@layout/custom_loading_view"
    app:ignore="NamespaceTypo">
        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/swipeLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            >
        <com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
        </android.support.v4.widget.SwipeRefreshLayout>
</com.lany.state.StateLayout>`

定义了没有生效。还是默认的loading view，其他没什么问题。

**Comment by lany192** [comment]
将你的 xmlns:app="http://schemas.android.com/tools" 改成xmlns:app="http://schemas.android.com/apk/res-auto"就可以了

**Comment by tmxd09887** [comment]
搞定了，谢谢。
